# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:

- name: DockerBuild
  script: |
    docker build -t redaptcloud/favorite-beer:$BUILD_TAG -f Dockerfile ../
  displayName: 'Run a docker build.'
  workingDirectory: "spa-react-netcore-redis/voting/voting"
  env:
    BUILD_TAG: $(Build.SourceVersion)
  continueOnError: false
  enabled: true
  timeoutInMinutes: 15
  failOnStderr: false


- script: |
    docker tag redaptcloud/favorite-beer:$BUILD_TAG redaptcloud/favorite-beer:latest
    docker push redaptcloud/favorite-beer:$BUILD_TAG
    docker push redaptcloud/favorite-beer:latest
  displayName: 'Tag and upload the build.'
  workingDirectory: "spa-react-netcore-redis/voting/voting"
  env:
    BUILD_TAG: $(Build.SourceVersion)

