# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
variables:
- group: redaptdemo
- name: variable_acr_name
  value: 'redaptdemo'

trigger:
- azure-pipelines


jobs:

# Set an output variable from job A
- job: DockerBuildAndPush
  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - script: |
      docker build -t $ACR_NAME.azurecr.io/favorite-beer:$BUILD_TAG -f Dockerfile ../
    name: "DockerBuild"
    displayName: 'Run a docker build.'
    workingDirectory: "spa-react-netcore-redis/voting/voting"
    env:
      BUILD_TAG: $(Build.SourceVersion)
      ACR_NAME: $(variable_acr_name)
    continueOnError: false
    enabled: true
    timeoutInMinutes: 15
    failOnStderr: false


  - script: |
      az login --service-principal --tenant $ARM_TENANT_ID -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET
      az acr login --name $ACR_NAME
      docker tag $ACR_NAME.azurecr.io/favorite-beer:$BUILD_TAG $ACR_NAME.azurecr.io/favorite-beer:latest
      docker push $ACR_NAME.azurecr.io/favorite-beer:$BUILD_TAG
      docker push $ACR_NAME.azurecr.io/favorite-beer:latest
    name: "DockerPush"
    displayName: 'Tag and upload the build.'
    workingDirectory: "spa-react-netcore-redis/voting/voting"
    env:
      BUILD_TAG: $(Build.SourceVersion)
      ARM_TENANT_ID: $(ext_variable_arm_tenant_id)
      ARM_CLIENT_ID: $(ext_variable_arm_client_id)
      ARM_CLIENT_SECRET: $(arm-client-secret)
      ACR_NAME: $(variable_acr_name)

  # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/helm-installer?view=azure-devops
  - task: HelmInstaller@0
    displayName: 'Install Helm'
    inputs:
      helmVersion: 2.14.1

  - bash: helm package --version $(build.buildId) --destination $(build.artifactStagingDirectory) .
    displayName: 'helm package'
    workingDirectory: "spa-react-netcore-redis/voting/voting/k8s/favorite-beer"

  - bash: az acr helm push -n $(variable_acr_name) $(build.artifactStagingDirectory)/favorite-beer-$(build.buildId).tgz
    displayName: 'az acr helm push'

  - bash: az acr helm repo add -n $(variable_acr_name)
    displayName: 'az acr helm repo add'

  - bash: helm search $(variable_acr_name)
    displayName: 'helm search'

  - bash: helm inspect $(variable_acr_name)/favorite-beer
    displayName: 'helm inspect'
