# Default values for favorite-beer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


servicesettings: |-
  {
    "ServiceSettings": {
      "Beers": ["Great Divide", "Epic", "Resolute", "Extra Beer"]
    }
  }