steps:
  - name: gcr.io/kaniko-project/executor:v0.15.0
    args: ["--dockerfile=voting/Dockerfile",
           "--destination=$TAG_NAME",
           "--cache=true",
           "--cache-dir=/cache",
           "--single-snapshot"]